version: '3.8'

services:
  AppsGateway:
    build:
      context: ./AppsGateway
      dockerfile: Dockerfile
  
  LifestylesApp:
    build:
      context: ./LifestylesApp
      dockerfile: Dockerfile
    environment:
      MYSQL_HOST:
      MYSQL_PORT:
      MYSQL_USERNAME:
      MYSQL_PASSWORD:
      KAFKA_BOOTSTRAP_ADDRESS:
      KAFKA_USERNAME:
      KAFKA_PASSWORD:

  FoodApp:
    build:
      context: ./FoodApp
      dockerfile: Dockerfile
    environment:
      KAFKA_BOOTSTRAP_ADDRESS:
      KAFKA_USERNAME:
      KAFKA_PASSWORD:
      FOOD_API_KEY:

  FootballApp:
    build:
      context: ./FootballApp
      dockerfile: Dockerfile
    environment:
      KAFKA_BOOTSTRAP_ADDRESS:
      KAFKA_USERNAME:
      KAFKA_PASSWORD:
      FOOTBALL_API_KEY:
